--grant ALL ON  BARANG TO ROLE "BARANG ALL";
--grant select ON BARANG TO ROLE "BARANG V";
--grant select, INSERT ON BARANG TO ROLE "BARANG VA";
--grant select, UPDATE ON BARANG TO ROLE "BARANG VE";
--grant select, DELETE ON BARANG TO ROLE "BARANG VD";
--grant select, INSERT, UPDATE ON BARANG TO ROLE "BARANG VAE";
--grant select, INSERT, DELETE ON BARANG TO ROLE "BARANG VAD";
--grant select, update,  DELETE ON BARANG TO ROLE "BARANG VED";
--GRANT USAGE ON SEQUENCE GEN$BARANG TO TRIGGER GENID_BARANG;

--grant ALL ON  "BARANG TL" TO ROLE "BARANG TL ALL";
--grant select ON BARANG TO ROLE "BARANG TL V";
--grant select, INSERT ON "BARANG TL" TO ROLE "BARANG TL VA";
--grant select, UPDATE ON "BARANG TL" TO ROLE "BARANG TL VE";
--grant select, DELETE ON "BARANG TL" TO ROLE "BARANG TL VD";
--grant select, INSERT, UPDATE ON "BARANG TL" TO ROLE "BARANG TL VAE";
--grant select, INSERT, DELETE ON "BARANG TL" TO ROLE "BARANG TL VAD";
--grant select, update,  DELETE ON "BARANG TL" TO ROLE "BARANG TL VED";
--GRANT USAGE ON SEQUENCE GEN$BARANGTL TO TRIGGER "GENID_BARANG TL";

--grant ALL ON  "DATA KELUAR" TO ROLE "DATA KELUAR ALL";
--grant select ON "DATA KELUAR" TO ROLE "DATA KELUAR V";
--grant select, INSERT ON "DATA KELUAR" TO ROLE "DATA KELUAR VA";
--grant select, UPDATE ON "DATA KELUAR" TO ROLE "DATA KELUAR VE";
--grant select, DELETE ON "DATA KELUAR" TO ROLE "DATA KELUAR VD";
--grant select, INSERT, UPDATE ON "DATA KELUAR" TO ROLE "DATA KELUAR VAE";
--grant select, INSERT, DELETE ON "DATA KELUAR" TO ROLE "DATA KELUAR VAD";
--grant select, update,  DELETE ON "DATA KELUAR" TO ROLE "DATA KELUAR VED";
--GRANT USAGE ON SEQUENCE GEN$DATAKELUAR TO TRIGGER "GENID_DATA KELUAR";

--grant ALL ON  "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR ALL";
--grant select ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR V";
--grant select, INSERT ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR VA";
--grant select, UPDATE ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR VE";
--grant select, DELETE ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR VD";
--grant select, INSERT, UPDATE ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR VAE";
--grant select, INSERT, DELETE ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR VAD";
--grant select, update,  DELETE ON "DATA KELUAR DETAIL" TO ROLE "DATA KELUAR VED";
--GRANT USAGE ON SEQUENCE GEN$DATAKELUARDETAIL TO TRIGGER "GENID_DATA KELUAR DETAIL";

--grant ALL ON  "DATA KELUAR TL" TO ROLE "DATA KELUAR TL ALL";
--grant select ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL V";
--grant select, INSERT ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL VA";
--grant select, UPDATE ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL VE";
--grant select, DELETE ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL VD";
--grant select, INSERT, UPDATE ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL VAE";
--grant select, INSERT, DELETE ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL VAD";
--grant select, update,  DELETE ON "DATA KELUAR TL" TO ROLE "DATA KELUAR TL VED";
--GRANT USAGE ON SEQUENCE GEN$DATAKELUARTL TO TRIGGER "GENID_DATA KELUAR TL"


--grant ALL ON  "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL ALL";
--grant select ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL V";
--grant select, INSERT ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL VA";
--grant select, UPDATE ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL VE";
--grant select, DELETE ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL VD";
--grant select, INSERT, UPDATE ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL VAE";
--grant select, INSERT, DELETE ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL VAD";
--grant select, update,  DELETE ON "DATA KELUAR DETAIL TL" TO ROLE "DATA KELUAR TL VED";
--GRANT USAGE ON SEQUENCE GEN$DATAKELUARDETAILTL TO TRIGGER "GENID_DATA KELUAR DETAIL TL";

--grant ALL ON  "DATA MASUK" TO ROLE "DATA MASUK ALL";
--grant select ON "DATA MASUK" TO ROLE "DATA MASUK V";
--grant select, INSERT ON "DATA MASUK" TO ROLE "DATA MASUK VA";
--grant select, UPDATE ON "DATA MASUK" TO ROLE "DATA MASUK VE";
--grant select, DELETE ON "DATA MASUK" TO ROLE "DATA MASUK VD";
--grant select, INSERT, UPDATE ON "DATA MASUK" TO ROLE "DATA MASUK VAE";
--grant select, INSERT, DELETE ON "DATA MASUK" TO ROLE "DATA MASUK VAD";
--grant select, update,  DELETE ON "DATA MASUK" TO ROLE "DATA MASUK VED";
--GRANT USAGE ON SEQUENCE GEN$DATAMASUK TO TRIGGER "GENID_DATA MASUK"

--grant ALL ON  "DATA MASUK TL" TO ROLE "DATA MASUK TL ALL";
--grant select ON "DATA MASUK TL" TO ROLE "DATA MASUK TL V";
--grant select, INSERT ON "DATA MASUK TL" TO ROLE "DATA MASUK TL VA";
--grant select, UPDATE ON "DATA MASUK TL" TO ROLE "DATA MASUK TL VE";
--grant select, DELETE ON "DATA MASUK TL" TO ROLE "DATA MASUK TL VD";
--grant select, INSERT, UPDATE ON "DATA MASUK TL" TO ROLE "DATA MASUK TL VAE";
--grant select, INSERT, DELETE ON "DATA MASUK TL" TO ROLE "DATA MASUK TL VAD";
--grant select, update,  DELETE ON "DATA MASUK TL" TO ROLE "DATA MASUK TL VED";
--GRANT USAGE ON SEQUENCE GEN$DATAMASUKTL TO TRIGGER "GENID_DATA MASUK TL"

--grant ALL ON  DEPARTEMEN TO ROLE "DEPARTEMEN ALL";
--grant select ON DEPARTEMEN TO ROLE "DEPARTEMEN V";
--grant select, INSERT ON DEPARTEMEN TO ROLE "DEPARTEMEN VA";
--grant select, UPDATE ON DEPARTEMEN TO ROLE "DEPARTEMEN VE";
--grant select, DELETE ON DEPARTEMEN TO ROLE "DEPARTEMEN VD";
--grant select, INSERT, UPDATE ON DEPARTEMEN TO ROLE "DEPARTEMEN VAE";
--grant select, INSERT, DELETE ON DEPARTEMEN TO ROLE "DEPARTEMEN VAD";
--grant select, update,  DELETE ON DEPARTEMEN TO ROLE "DEPARTEMEN VED";
--GRANT USAGE ON SEQUENCE GEN$DEPARTEMEN TO TRIGGER "GENID_DEPARTEMEN"

--grant ALL ON  "UKURAN TL" TO ROLE "UKURAN TL ALL";
--grant select ON "UKURAN TL" TO ROLE "UKURAN TL V";
--grant select, INSERT ON "UKURAN TL" TO ROLE "UKURAN TL VA";
--grant select, UPDATE ON "UKURAN TL" TO ROLE "UKURAN TL VE";
--grant select, DELETE ON "UKURAN TL" TO ROLE "UKURAN TL VD";
--grant select, INSERT, UPDATE ON "UKURAN TL" TO ROLE "UKURAN TL VAE";
--grant select, INSERT, DELETE ON "UKURAN TL" TO ROLE "UKURAN TL VAD";
--grant select, update,  DELETE ON "UKURAN TL" TO ROLE "UKURAN TL VED";
--GRANT USAGE ON SEQUENCE GEN$UKURANTL TO TRIGGER "GENID_UKURAN TL"

--grant ALL ON  UNIT TO ROLE "UNIT ALL";
--grant select ON UNIT TO ROLE "UNIT V";
--grant select, INSERT ON UNIT TO ROLE "UNIT VA";
--grant select, UPDATE ON UNIT TO ROLE "UNIT VE";
--grant select, DELETE ON UNIT TO ROLE "UNIT VD";
--grant select, INSERT, UPDATE ON UNIT TO ROLE "UNIT VAE";
--grant select, INSERT, DELETE ON UNIT TO ROLE "UNIT VAD";
--grant select, update,  DELETE ON UNIT TO ROLE "UNIT VED";
--GRANT USAGE ON SEQUENCE GEN$UNIT TO TRIGGER "GENID_UNIT"

--grant select on "VIEW STOK PE BY LOT" to "STOK PE BY LOT V";
--grant select on "VIEW STOK PE BY BARANG" to "STOK PE BY BARANG V";
--grant select on "VIEW STOK PE ALL" to "STOK PE ALL";

--GRANT SELECT ON "DAFTAR_USER" TO "DAFTAR USER DATA";

--grant select on "VIEW STOK TL BY LOT" to "STOK TL BY LOT V";
--grant select on "VIEW STOK TL BY BARANG" to "STOK TL BY BARANG V";
--grant select on "VIEW STOK TL BY UKURAN" to "STOK TL BY UKURAN V";
--grant select on "VIEW STOK TL ALL" to "STOK TL ALL";


--grant select, delete, insert, update on "TEMP DATA KELUAR DETAIL"  to "TEMP DATA KELUAR PUBLIC";
--grant select, delete, insert, update on "TEMP DATA KELUAR DETAIL TL"  to "TEMP DATA KELUAR TL PUBLIC";

--grant "TEMP DATA KELUAR PUBLIC" TO PUBLIC;
--grant "TEMP DATA KELUAR TL PUBLIC" TO PUBLIC;

--grant insert on "LOG" TO PUBLIC; --agar semua user bisa insert ke log (bila ada add, edit, delete)
--grant select ON "LOG" TO "LOG V";
--GRANT EXECUTE ON PROCEDURE PROC_INSERT_LOG TO PUBLIC;

--grant usage on GENERATOR RDB$3 TO USE_GBAK;
--grant usage on GENERATOR RDB$9 TO USE_GBAK;
--grant usage on GENERATOR RDB$7 TO USE_GBAK;
--grant usage on GENERATOR RDB$8 TO USE_GBAK;
-- grant default  USE_GBAK to BACKUPDB;


--grant insert on plg$srp_view TO "USER A"

--CREATE view "STOK BARANG PE" AS
--select
--A.id_barang, B."NAMA BARANG",
--SUM(A."JUMLAH MASUK") "JUMLAH MASUK",
--SUM(A."JUMLAH KELUAR") "JUMLAH KELUAR" ,
--SUM(A."JUMLAH SISA") "JUMLAH SISA",
--SUM(A."BERAT MASUK") "BERAT MASUK",
--SUM(A."BERAT KELUAR") "BERAT KELUAR",
--SUM(A."BERAT SISA") "BERAT SISA"
-- FROM "STOK BARANG" A
--LEFT JOIN BARANG B ON B.ID = A.ID_BARANG
--GROUP BY A.ID_BARANG, B."NAMA BARANG"
--

--CREATE view "VIEW STOK BARANG TL" AS
--select
--A."ID_BARANG TL", B."NAMA BARANG",
--SUM(A."JUMLAH MASUK") "JUMLAH MASUK",
--SUM(A."JUMLAH KELUAR") "JUMLAH KELUAR" ,
--SUM(A."JUMLAH SISA") "JUMLAH SISA",
--SUM(A."BERAT MASUK") "BERAT MASUK",
--SUM(A."BERAT KELUAR") "BERAT KELUAR",
--SUM(A."BERAT SISA") "BERAT SISA"
-- FROM "STOK BARANG TL" A
--LEFT JOIN "BARANG TL" B ON B.ID = A."ID_BARANG TL"
--GROUP BY A."ID_BARANG TL", B."NAMA BARANG"



--grant "BARANG V" to NIMAS WITH ADMIN OPTION;
--grant "BARANG VA" to NIMAS WITH ADMIN OPTION;
--grant "BARANG VE" to NIMAS WITH ADMIN OPTION;

--revoke "BARANG VD" FROM NIMAS;
--grant "BARANG VD" TO NIMAS;

--grant "DATA MASUK V" to NIMAS WITH ADMIN OPTION;
--grant "DATA MASUK VA" to NIMAS WITH ADMIN OPTION;
--grant "DATA MASUK VE" to NIMAS WITH ADMIN OPTION;

--revoke "DATA MASUK VD" FROM NIMAS;
--grant "DATA MASUK VD" TO NIMAS;


--grant "DATA KELUAR V" to NIMAS WITH ADMIN OPTION;
--grant "DATA KELUAR VA" to NIMAS WITH ADMIN OPTION;
--grant "DATA KELUAR VE" to NIMAS WITH ADMIN OPTION;

--revoke "DATA KELUAR VD" FROM NIMAS;
--grant "DATA KELUAR VD" TO NIMAS;

--grant "UNIT V" to NIMAS WITH ADMIN OPTION;
--grant "UNIT VA" to NIMAS WITH ADMIN OPTION;
--grant "UNIT VE" to NIMAS WITH ADMIN OPTION;

--revoke "UNIT VD" FROM NIMAS;
--grant "UNIT VD" TO NIMAS;

--grant "DEPARTEMEN V" to NIMAS WITH ADMIN OPTION;
--grant "DEPARTEMEN VA" to NIMAS WITH ADMIN OPTION;
--grant "DEPARTEMEN VE" to NIMAS WITH ADMIN OPTION;

--revoke "DEPARTEMEN VD" FROM NIMAS;
--grant "DEPARTEMEN VD" TO NIMAS;
--grant "DAFTAR USER DATA" TO NIMAS;

--grant MANAGE_USERS to NIMAS; ini entah buat apa nanti cari tahuN
--grant "USER A" TO NIMAS ;    --INI BUAT NAMBAH USER


--grant "STOK PE BY LOT V" TO NIMAS WITH ADMIN OPTION;
--grant "STOK PE BY BARANG V" TO NIMAS WITH ADMIN OPTION;
--grant "STOK PE ALL" TO NIMAS WITH ADMIN OPTION;


--NIMAS password 'nimaspe123'



--grant "BARANG TL V" to ANJAR WITH ADMIN OPTION;
--grant "BARANG TL VA" to ANJAR WITH ADMIN OPTION;
--grant "BARANG TL VE" to ANJAR WITH ADMIN OPTION;

--revoke "BARANG TL VD" FROM ANJAR;
--grant "BARANG TL VD" TO ANJAR;

--grant "DATA MASUK TL V" to ANJAR WITH ADMIN OPTION;
--grant "DATA MASUK TL VA" to ANJAR WITH ADMIN OPTION;
--grant "DATA MASUK TL VE" to ANJAR WITH ADMIN OPTION;

--revoke "DATA MASUK TL VD" FROM ANJAR;
--grant "DATA MASUK TL VD" TO ANJAR;

--grant "DATA KELUAR TL V" to ANJAR WITH ADMIN OPTION;
--grant "DATA KELUAR TL VA" to ANJAR WITH ADMIN OPTION;
--grant "DATA KELUAR TL VE" to ANJAR WITH ADMIN OPTION;

--revoke "DATA KELUAR TL VD" FROM ANJAR;
--grant "DATA KELUAR TL VD" TO ANJAR;

--grant "UNIT V" to ANJAR WITH ADMIN OPTION;
--grant "UNIT VA" to ANJAR WITH ADMIN OPTION;
--grant "UNIT VE" to ANJAR WITH ADMIN OPTION;

--revoke "UNIT VD" FROM ANJAR;
--grant "UNIT VD" TO ANJAR;

--grant "DEPARTEMEN V" to ANJAR WITH ADMIN OPTION;
--grant "DEPARTEMEN VA" to ANJAR WITH ADMIN OPTION;
--grant "DEPARTEMEN VE" to ANJAR WITH ADMIN OPTION;

--revoke "DEPARTEMEN VD" FROM ANJAR;
--grant "DEPARTEMEN VD" TO ANJAR;

--grant "UKURAN TL V" to ANJAR WITH ADMIN OPTION;
--grant "UKURAN TL VA" to ANJAR WITH ADMIN OPTION;
--grant "UKURAN TL VE" to ANJAR WITH ADMIN OPTION;

--revoke "UKURAN TL VD" FROM ANJAR;
--grant "UKURAN TL VD" TO ANJAR;

--   //VIEW DAFTAR USER
--grant "DAFTAR USER DATA" TO ANJAR;
--grant "MANAGE_USERS" to ANJAR;  INI ENTAH BUAT APA NANTI CARI TAHU
--grant "USER A" TO ANJAR ;    --INI BUAT NAMBAH USER

--grant "STOK TL BY LOT V" TO ANJAR WITH ADMIN OPTION;
--grant "STOK TL BY BARANG V" TO ANJAR WITH ADMIN OPTION;
--grant "STOK TL BY UKURAN V" TO ANJAR WITH ADMIN OPTION;
--grant "STOK TL ALL" TO ANJAR WITH ADMIN OPTION;

--grant usage on generator GEN$DB_BULAN TO NIMAS;
--GRANT USAGE ON GENERATOR GEN$BA_PE TO NIMAS;

--grant usage on generator GEN$DB_BULAN TO ANJAR;

--grant usage on generator GEN$DB_BULAN TO RESETTERGEN;
--GRANT USAGE ON GENERATOR GEN$BA_PE TO RESETTERGEN;
--grant execute on procedure "PROC RESET GEN ID" to RESETTERGEN;

--grant select on "VIEW DATA KELUAR PE" TO NIMAS;  //untuk ekspor ke excel
--grant select on "VIEW DATA KELUAR TL" TO ANJAR; //untuk ekspor ke excel

--ANJAR password 'anjartali123'
--RESETTERGEN password 'janganlupa'



