CREATE VIEW "VIEW STOK PE BY BARANG"
AS
select
B.id_barang, B."NAMA BARANG",
SUM(B."JUMLAH MASUK") "JUMLAH MASUK", SUM(B."BERAT MASUK") "BERAT MASUK",
SUM(B."JUMLAH KELUAR")"JUMLAH KELUAR" , SUM(B."BERAT KELUAR") "BERAT KELUAR",
SUM(B."JUMLAH SISA") "JUMLAH SISA", SUM(B."BERAT SISA") "BERAT SISA"

FROM "VIEW STOK PE BY LOT" B

GROUP BY  B.id_barang, B."NAMA BARANG"
